name: stacktrace_impl
version: 1.0.0
homepage: https://github.com/bsutton/stacktrace_impl
description: Allows you to instantiate a StackTrace and provides logging control.
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  path: ^1.7.0
dev_dependencies: 
  pedantic: ^1.9.0
  test: 1.15.4
